version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: api_gateway_postgres_prod
    environment:
      POSTGRES_DB: api_gateway
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - api_gateway_network_prod
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Kong Database
  kong-database:
    image: postgres:15-alpine
    container_name: kong_postgres_prod
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: ${KONG_DB_PASSWORD:-kong}
    volumes:
      - kong_data_prod:/var/lib/postgresql/data
    networks:
      - api_gateway_network_prod
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kong"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Kong Database Migration
  kong-migration:
    image: kong:3.4-alpine
    container_name: kong_migration_prod
    command: "kong migrations bootstrap"
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_DATABASE: kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: ${KONG_DB_PASSWORD:-kong}
    networks:
      - api_gateway_network_prod
    depends_on:
      kong-database:
        condition: service_healthy
    restart: on-failure

  # Kong Gateway
  kong:
    image: kong:3.4-alpine
    container_name: kong_gateway_prod
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_DATABASE: kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: ${KONG_DB_PASSWORD:-kong}
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
    ports:
      - "8000:8000"  # Kong Proxy
      - "8443:8443"  # Kong Proxy SSL
      - "8001:8001"  # Kong Admin API
      - "8444:8444"  # Kong Admin API SSL
      - "8002:8002"  # Kong Manager
    networks:
      - api_gateway_network_prod
    depends_on:
      kong-migration:
        condition: service_completed_successfully
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10

  # Redis for caching and rate limiting
  redis:
    image: redis:7-alpine
    container_name: api_gateway_redis_prod
    ports:
      - "6379:6379"
    networks:
      - api_gateway_network_prod
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api_gateway_backend_prod
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD:-postgres}@postgres:5432/api_gateway
      REDIS_URL: redis://redis:6379
      SECRET_KEY: ${JWT_SECRET_KEY:-your-secret-key-change-in-production}
    ports:
      - "8000:8000"
    networks:
      - api_gateway_network_prod
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # API Gateway (Rust)
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api_gateway_rust_prod
    environment:
      GATEWAY_CONFIG: |
        {
          "server": {
            "host": "0.0.0.0",
            "port": 8080
          },
          "routes": [
            {
              "path": "/api/v1/*",
              "method": null,
              "backend": "backend_api",
              "load_balancing": "round_robin",
              "rate_limit": 100,
              "auth_required": true,
              "timeout_ms": 30000
            }
          ],
          "backends": {
            "backend_api": {
              "name": "Backend API",
              "servers": ["http://backend:8000"],
              "health_check": {
                "enabled": true,
                "path": "/health",
                "interval_seconds": 30,
                "timeout_seconds": 5,
                "healthy_threshold": 2,
                "unhealthy_threshold": 3
              },
              "circuit_breaker": {
                "enabled": true,
                "failure_threshold": 5,
                "recovery_timeout_seconds": 60
              }
            }
          },
          "rate_limiting": {
            "enabled": true,
            "default_requests_per_minute": 60,
            "burst_size": 10,
            "storage": "redis"
          },
          "auth": {
            "enabled": true,
            "jwt_secret": "${JWT_SECRET_KEY:-your-jwt-secret-key}",
            "api_key_header": "X-API-Key",
            "bypass_paths": ["/health", "/metrics", "/auth/login", "/public/*"]
          },
          "redis": {
            "url": "redis://redis:6379",
            "pool_size": 10
          },
          "database": {
            "url": "postgresql://postgres:${POSTGRES_PASSWORD:-postgres}@postgres:5432/api_gateway",
            "max_connections": 10
          }
        }
    ports:
      - "8080:8080"
    networks:
      - api_gateway_network_prod
    depends_on:
      backend:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: api_gateway_frontend_prod
    ports:
      - "3000:80"
    networks:
      - api_gateway_network_prod
    depends_on:
      - api-gateway
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data_prod:
  kong_data_prod:

networks:
  api_gateway_network_prod:
    driver: bridge 