version: '3.8'

# This is the main branch - for working setups, choose a specific approach:
# 
# For Kong Gateway:     git checkout kong-gateway
# For Rust Gateway:     git checkout rust-gateway
#
# Each branch has a clean, focused implementation without conflicts.

services:
  # This file is intentionally minimal on main branch.
  # Switch to kong-gateway or rust-gateway branches for working setups.
  
  placeholder:
    image: hello-world
    container_name: main_branch_placeholder
    restart: "no"

networks:
  api_gateway_network:
    driver: bridge 